version: '3'
services:
  episodecalendar:
    build: .
    network_mode: 'host'
  transmission:
    image: linuxserver/transmission:latest
    network_mode: 'host'
    volumes:
      - /c/Users/matt/Videos:/downloads